# Generated by Django 6.0.4 on 2026-04-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=25, verbose_name='Karta raqami')),
                ('expiry_date', models.CharField(max_length=20, verbose_name='Amal qilish muddati')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=10, verbose_name='Holati')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Balans')),
            ],
            options={
                'verbose_name': 'Karta',
                'verbose_name_plural': 'Kartalar',
            },
        ),
    ]
