# Generated by Django 6.0.4 on 2026-04-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_0002_transfer_error_0003_card_telegram_chat_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transfer',
            new_name='app_transfe_ext_id_28338c_idx',
            old_name='app_transfe_ext_id_0eec4d_idx',
        ),
        migrations.RenameIndex(
            model_name='transfer',
            new_name='app_transfe_sender__2c06f1_idx',
            old_name='app_transfe_sender__1d5e24_idx',
        ),
        migrations.RenameIndex(
            model_name='transfer',
            new_name='app_transfe_receive_3b92ff_idx',
            old_name='app_transfe_receive_9978ab_idx',
        ),
        migrations.RenameIndex(
            model_name='transfer',
            new_name='app_transfe_state_4b42b6_idx',
            old_name='app_transfe_state_87f146_idx',
        ),
        migrations.RenameIndex(
            model_name='transfer',
            new_name='app_transfe_created_2f6e2b_idx',
            old_name='app_transfe_created_2bf7d4_idx',
        ),
    ]
