# Generated by Django 4.2.29 on 2026-04-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_app_transfe_ext_id_0eec4d_idx_app_transfe_ext_id_28338c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='currency',
            field=models.CharField(choices=[('uzs', 'uzs'), ('usd', 'usd'), ('rub', 'rub')], default='uzs', max_length=16),
        ),
    ]
